from typing import List, Optional, Union

import hydra
import pytorch_lightning as pl
from omegaconf import DictConfig

import src.utilities.config_utils as cfg_utils
from src.interface import get_model_and_data
from src.utilities.hub import get_forecaster_checkpoint
from src.utilities.utils import get_logger


log = get_logger(__name__)


def run_inference(config: DictConfig) -> Optional[Union[float, List[float]]]:
    """Run inference (test/predict) on a trained model.

    Args:
        config: A DictConfig object generated by hydra containing the model, data, callbacks & trainer configuration.

    Returns:
        Optional metric value from the test run.
    """
    pl.seed_everything(config.seed)
    config = cfg_utils.extras(config)

    ckpt_path = get_forecaster_checkpoint(config.get("ckpt_path"))

    model, datamodule = get_model_and_data(config)

    if config.get("only_resume_weight") is True and ckpt_path is not None:
        log.info(f"Loading model weights from {ckpt_path}")
        model = model.__class__.load_from_checkpoint(ckpt_path, **model.hparams)
        ckpt_path = None

    callbacks = cfg_utils.get_all_instantiable_hydra_modules(config, "callbacks")

    trainer: pl.Trainer = hydra.utils.instantiate(config.trainer, callbacks=callbacks, logger=False)

    test_what = {"ckpt_path": ckpt_path, "model": model}
    trainer.test(datamodule=datamodule, **test_what)

    metric_dict = trainer.callback_metrics
    return metric_dict


@hydra.main(config_path="configs/", config_name="main_config.yaml", version_base=None)
def main(config: DictConfig) -> float:
    """Run inference based on the config file configs/main_config.yaml (and any command-line overrides)."""
    return run_inference(config)


if __name__ == "__main__":
    main()
